### ISSUE TITLE
Max/Min Expressions in Utils.scala

### ISSUE THREAD

**Issue by oshritf** [ucbrise/opaque#23]
Max/Min throws null exception when column is other than IntegerType

More info:
scala/edu/berkeley/cs/rise/opaque/Utils.scala:

flatbuffersCreateField supports only creation of Null IntegerType (sets int value to 0) 
Max and Min methods create Null Literal which currently not fully supported for all DataTypes and results in an exception.

Setting init value to zero (default for IntegerType currently) might not return valid results when data contains also negative values.

**Comment by ankurdave** [comment]
Thanks, we need to support serializing nulls of other types than IntegerType.

> Setting init value to zero (default for IntegerType currently) might not return valid results when data contains also negative values.

I don't think this should occur, because the aggregate expressions do perform null checks ([e.g. for Max](https://github.com/ucbrise/opaque/blob/80346b7085043cb9acd292514b80395bce424a74/src/main/scala/edu/berkeley/cs/rise/opaque/Utils.scala#L828)). The zero is only there as a placeholder.

**Comment by ankurdave** [comment]
Moved the second part of this issue to #25.

**Comment by oshritf** [comment]
scala.MatchError: (null,LongType) (of class scala.Tuple2)
at edu.berkeley.cs.rise.opaque.Utils$.flatbuffersCreateField(Utils.scala:256)
When performing select max/min/count with groupby on DoubleType or LongType columns

origins - creation of Literal.create(null, child.dataType) in createInitialValuesVector
